
version: '2.0'

# services
services:
  webauth:
    build: ..
    image: lcas.lincoln.ac.uk/lcas/webauth:master
    restart: always
    volumes:
    - /srv/webauth:/mnt/webauth:rw
    ports:
    - 8099:8099
    - 9443:8443
    command: ["--config=/mnt/webauth/config/config.yaml", "--logging=debug"]
    entrypoint: ["python3", '-m', 'trace', "-T", "./webauth"]
